### PR TITLE
Reorganize directory structure

### PR DESCRIPTION
**Pull request by stevescavo**
- Reorganize and improve folder structure
- Cleanup various nomenclature

### CODE REVIEW

**Comment by unruffledBeaver** [comment]
We should throw `Bundle` into `containers`.

**Comment by stevescavo** [comment]
@unruffledBeaver I'm gonna do that.

**Comment by rynocouse** [comment]
Wait, since we're on this we should pull out magic imports

**Comment by stevescavo** [comment]
@unruffledBeaver @rynocouse https://github.com/MadeInHaus/react-redux-webpack-starter/pull/35/commits/8236770a1c1cae644335a6d4af9cdc16cd6e03bc

**Comment by stevescavo** [comment]
If we're all good on this, I'd like to merge :)

**Pull request merged**
